set(_CATKIN_CURRENT_PACKAGE "mobile_sensor_system")
set(mobile_sensor_system_VERSION "0.0.0")
set(mobile_sensor_system_MAINTAINER "pcmobielerobot <pcmobielerobot@todo.todo>")
set(mobile_sensor_system_PACKAGE_FORMAT "2")
set(mobile_sensor_system_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "message_generation")
set(mobile_sensor_system_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(mobile_sensor_system_BUILDTOOL_DEPENDS "catkin")
set(mobile_sensor_system_BUILDTOOL_EXPORT_DEPENDS )
set(mobile_sensor_system_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "message_runtime")
set(mobile_sensor_system_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(mobile_sensor_system_TEST_DEPENDS )
set(mobile_sensor_system_DOC_DEPENDS )
set(mobile_sensor_system_URL_WEBSITE "")
set(mobile_sensor_system_URL_BUGTRACKER "")
set(mobile_sensor_system_URL_REPOSITORY "")
set(mobile_sensor_system_DEPRECATED "")